name: Docker Publish

on:
  [push]
  # push:
  #   # Publish `master` as Docker `latest` image
  #   branches:
  #     - master
  #   # Publish `v1.2.3` tags as releases
  #   tags:
  #     - v*
  # Run tests for any PRs
  # pull_requests:

env:
  # Your image's name
  IMAGE_NAME: "test-app-ci-cd"

jobs:
  # Run tests
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run tests
  #       run: docker build . --file Dockerfile
  #       # run: |
  #       #   if [ -f docker-compose.test.yml ]; then
  #       #     docker-compose --file docker-compose.test.yml build
  #       #     docker-compose --file docker-compose.test.yml run sut
  #       #   else
  #       #     docker build . --file Dockerfile
  #       #   fi

  # Push image to Docker Hub
  push:
    # Ensure test job passes before pushing
    # needs: test

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t eli9000/$IMAGE_NAME:latest .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: eli9000/test-app-ci-cd
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PW }}
        # run: docker push eli9000/test-app-ci-cd:latest
